name: Preview resource_ingest_guide_schema documentation build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.10

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Build documentation
        run: |
          mkdir -p site
          touch site/.nojekyll
          make gendoc
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          uv run mkdocs build -d site

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site/
          preview-branch: gh-pages
